version: '3.7'

services:
  postgres_uniticket:
    image: postgres
    container_name: postgres_uniticket
    hostname: uniticket_db
    environment:
      - 'POSTGRES_USER='
      - 'POSTGRES_PASSWORD='
      - 'POSTGRES_DB='
    ports:
      - 5432:5432

  postgres_test_uniticket:
    image: postgres
    container_name: postgres_test_uniticket
    hostname: uniticket_test_db
    environment:
      - 'POSTGRES_USER='
      - 'POSTGRES_PASSWORD='
      - 'POSTGRES_DB='
    ports:
      - 5433:5432

  redis_uniticket:
    image: redis
    container_name: redis_uniticket
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379

  uniticket_api:
    build:
      context: .
    container_name: uniticket_api
    ports:
      - 5000:5000
    environment:
      # General
      - 'FRONTEND_URL='
      - 'NODE_ENV='

      # Secret
      - 'JWT_SECRET='
      - 'JWT_EXPIRATION_TIME='

      # Postgres
      - 'POSTGRES_HOST='
      - 'POSTGRES_PORT='
      - 'POSTGRES_URL='
      - 'POSTGRES_TEST_URL='

      # Redis
      - 'REDIS_PASSWORD='

      # Mail
      - 'MAIL_HOST='
      - 'MAIL_PORT='
      - 'MAIL_USER='
      - 'MAIL_PASS='
